### PR TITLE
Added Champaign County Coalition

### PR DESCRIPTION
**Pull request by Kassmanben**

### CODE REVIEW

**Comment by goldenercobra** [comment]
Hi there! Champaign County Coalition has not been confirmed to support protestors yet, hence why they have not been added to the list. If they are I can add them, but until then I'm living this pull request open.

**Comment by Kassmanben** [comment]
> Hi there! Champaign County Coalition has not been confirmed to support protestors yet, hence why they have not been added to the list. If they are I can add them, but until then I'm living this pull request open.

Thanks! I added a Pr for something showing this info in the Readme, so people wanting to help aren't duplicating the work I did of cross-referencing the NBFN site with the current one without cause. Thanks so much for doing this 😄

**Comment by MetricMike** [comment]
Post specifically supporting bail for protesters
https://champaigncountybailoutcoalition.wordpress.com/2020/06/02/free-all-protestors-in-champaign-county/

**Comment by andyzwang** [comment]
This looks good to me !

**Pull request closed without merging**
